package com.rs.hr.modules.sys.entity;

import com.baomidou.mybatisplus.annotation.TableId;

public class SysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    @TableId
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_key
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.status
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.remark
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_value
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public SysConfig withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_key
     *
     * @return the value of sys_config.config_key
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public SysConfig withConfigKey(String configKey) {
        this.setConfigKey(configKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_key
     *
     * @param configKey the value for sys_config.config_key
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.status
     *
     * @return the value of sys_config.status
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public SysConfig withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.status
     *
     * @param status the value for sys_config.status
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.remark
     *
     * @return the value of sys_config.remark
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public SysConfig withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.remark
     *
     * @param remark the value for sys_config.remark
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_value
     *
     * @return the value of sys_config.config_value
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public SysConfig withConfigValue(String configValue) {
        this.setConfigValue(configValue);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_value
     *
     * @param configValue the value for sys_config.config_value
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysConfig other = (SysConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConfigKey() == null ? other.getConfigKey() == null : this.getConfigKey().equals(other.getConfigKey()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getConfigValue() == null ? other.getConfigValue() == null : this.getConfigValue().equals(other.getConfigValue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConfigKey() == null) ? 0 : getConfigKey().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getConfigValue() == null) ? 0 : getConfigValue().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu May 21 14:41:37 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", configKey=").append(configKey);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", configValue=").append(configValue);
        sb.append("]");
        return sb.toString();
    }
}