package com.rs.hr.modules.sys.entity;

import java.util.Date;

public class SysGoogleAuthKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.auth_key_id
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private String authKeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.username
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.secret
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.create_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.modify_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.reset_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private Boolean resetFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.status_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private Boolean statusFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_google_auth_key.del_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.auth_key_id
     *
     * @return the value of sys_google_auth_key.auth_key_id
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public String getAuthKeyId() {
        return authKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withAuthKeyId(String authKeyId) {
        this.setAuthKeyId(authKeyId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.auth_key_id
     *
     * @param authKeyId the value for sys_google_auth_key.auth_key_id
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setAuthKeyId(String authKeyId) {
        this.authKeyId = authKeyId == null ? null : authKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.username
     *
     * @return the value of sys_google_auth_key.username
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.username
     *
     * @param username the value for sys_google_auth_key.username
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.secret
     *
     * @return the value of sys_google_auth_key.secret
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withSecret(String secret) {
        this.setSecret(secret);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.secret
     *
     * @param secret the value for sys_google_auth_key.secret
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.create_time
     *
     * @return the value of sys_google_auth_key.create_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.create_time
     *
     * @param createTime the value for sys_google_auth_key.create_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.modify_time
     *
     * @return the value of sys_google_auth_key.modify_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withModifyTime(Date modifyTime) {
        this.setModifyTime(modifyTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.modify_time
     *
     * @param modifyTime the value for sys_google_auth_key.modify_time
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.reset_flag
     *
     * @return the value of sys_google_auth_key.reset_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public Boolean getResetFlag() {
        return resetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withResetFlag(Boolean resetFlag) {
        this.setResetFlag(resetFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.reset_flag
     *
     * @param resetFlag the value for sys_google_auth_key.reset_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setResetFlag(Boolean resetFlag) {
        this.resetFlag = resetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.status_flag
     *
     * @return the value of sys_google_auth_key.status_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public Boolean getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withStatusFlag(Boolean statusFlag) {
        this.setStatusFlag(statusFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.status_flag
     *
     * @param statusFlag the value for sys_google_auth_key.status_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setStatusFlag(Boolean statusFlag) {
        this.statusFlag = statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_google_auth_key.del_flag
     *
     * @return the value of sys_google_auth_key.del_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public SysGoogleAuthKey withDelFlag(Boolean delFlag) {
        this.setDelFlag(delFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_google_auth_key.del_flag
     *
     * @param delFlag the value for sys_google_auth_key.del_flag
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysGoogleAuthKey other = (SysGoogleAuthKey) that;
        return (this.getAuthKeyId() == null ? other.getAuthKeyId() == null : this.getAuthKeyId().equals(other.getAuthKeyId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getSecret() == null ? other.getSecret() == null : this.getSecret().equals(other.getSecret()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getResetFlag() == null ? other.getResetFlag() == null : this.getResetFlag().equals(other.getResetFlag()))
            && (this.getStatusFlag() == null ? other.getStatusFlag() == null : this.getStatusFlag().equals(other.getStatusFlag()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAuthKeyId() == null) ? 0 : getAuthKeyId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getSecret() == null) ? 0 : getSecret().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getResetFlag() == null) ? 0 : getResetFlag().hashCode());
        result = prime * result + ((getStatusFlag() == null) ? 0 : getStatusFlag().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_google_auth_key
     *
     * @mbg.generated Wed May 20 10:56:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authKeyId=").append(authKeyId);
        sb.append(", username=").append(username);
        sb.append(", secret=").append(secret);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", resetFlag=").append(resetFlag);
        sb.append(", statusFlag=").append(statusFlag);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}