package com.rs.hr.modules.sys.entity;

import com.baomidou.mybatisplus.annotation.TableId;

import java.util.Date;

public class SysUserToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    @TableId
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.user_id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.expire_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.update_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.id
     *
     * @return the value of sys_user_token.id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public SysUserToken withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.id
     *
     * @param id the value for sys_user_token.id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.user_id
     *
     * @return the value of sys_user_token.user_id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public SysUserToken withUserId(String userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.user_id
     *
     * @param userId the value for sys_user_token.user_id
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.token
     *
     * @return the value of sys_user_token.token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public SysUserToken withToken(String token) {
        this.setToken(token);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.token
     *
     * @param token the value for sys_user_token.token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.expire_time
     *
     * @return the value of sys_user_token.expire_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public SysUserToken withExpireTime(Date expireTime) {
        this.setExpireTime(expireTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.expire_time
     *
     * @param expireTime the value for sys_user_token.expire_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.update_time
     *
     * @return the value of sys_user_token.update_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public SysUserToken withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.update_time
     *
     * @param updateTime the value for sys_user_token.update_time
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUserToken other = (SysUserToken) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getExpireTime() == null ? other.getExpireTime() == null : this.getExpireTime().equals(other.getExpireTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getExpireTime() == null) ? 0 : getExpireTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Tue May 19 13:31:42 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", token=").append(token);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}