package com.rs.hr.modules.resume.entity;

import java.math.BigDecimal;

public class UserInviteCommission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.user_invite_commission_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long userInviteCommissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.team_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.invite_user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long inviteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.operation_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Integer operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.lvl
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Integer lvl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.rate
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.commission_sum
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private BigDecimal commissionSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.ref_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.memo
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.create_time
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite_commission.state_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    private Byte stateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.user_invite_commission_id
     *
     * @return the value of user_invite_commission.user_invite_commission_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getUserInviteCommissionId() {
        return userInviteCommissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withUserInviteCommissionId(Long userInviteCommissionId) {
        this.setUserInviteCommissionId(userInviteCommissionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.user_invite_commission_id
     *
     * @param userInviteCommissionId the value for user_invite_commission.user_invite_commission_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setUserInviteCommissionId(Long userInviteCommissionId) {
        this.userInviteCommissionId = userInviteCommissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.team_id
     *
     * @return the value of user_invite_commission.team_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withTeamId(Long teamId) {
        this.setTeamId(teamId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.team_id
     *
     * @param teamId the value for user_invite_commission.team_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.user_id
     *
     * @return the value of user_invite_commission.user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.user_id
     *
     * @param userId the value for user_invite_commission.user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.invite_user_id
     *
     * @return the value of user_invite_commission.invite_user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getInviteUserId() {
        return inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withInviteUserId(Long inviteUserId) {
        this.setInviteUserId(inviteUserId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.invite_user_id
     *
     * @param inviteUserId the value for user_invite_commission.invite_user_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setInviteUserId(Long inviteUserId) {
        this.inviteUserId = inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.operation_type
     *
     * @return the value of user_invite_commission.operation_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withOperationType(Integer operationType) {
        this.setOperationType(operationType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.operation_type
     *
     * @param operationType the value for user_invite_commission.operation_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.lvl
     *
     * @return the value of user_invite_commission.lvl
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Integer getLvl() {
        return lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withLvl(Integer lvl) {
        this.setLvl(lvl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.lvl
     *
     * @param lvl the value for user_invite_commission.lvl
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setLvl(Integer lvl) {
        this.lvl = lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.rate
     *
     * @return the value of user_invite_commission.rate
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withRate(BigDecimal rate) {
        this.setRate(rate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.rate
     *
     * @param rate the value for user_invite_commission.rate
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.commission_sum
     *
     * @return the value of user_invite_commission.commission_sum
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public BigDecimal getCommissionSum() {
        return commissionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withCommissionSum(BigDecimal commissionSum) {
        this.setCommissionSum(commissionSum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.commission_sum
     *
     * @param commissionSum the value for user_invite_commission.commission_sum
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setCommissionSum(BigDecimal commissionSum) {
        this.commissionSum = commissionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.ref_id
     *
     * @return the value of user_invite_commission.ref_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withRefId(Long refId) {
        this.setRefId(refId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.ref_id
     *
     * @param refId the value for user_invite_commission.ref_id
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.memo
     *
     * @return the value of user_invite_commission.memo
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withMemo(String memo) {
        this.setMemo(memo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.memo
     *
     * @param memo the value for user_invite_commission.memo
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.create_time
     *
     * @return the value of user_invite_commission.create_time
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withCreateTime(Long createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.create_time
     *
     * @param createTime the value for user_invite_commission.create_time
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite_commission.state_type
     *
     * @return the value of user_invite_commission.state_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public Byte getStateType() {
        return stateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public UserInviteCommission withStateType(Byte stateType) {
        this.setStateType(stateType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite_commission.state_type
     *
     * @param stateType the value for user_invite_commission.state_type
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    public void setStateType(Byte stateType) {
        this.stateType = stateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInviteCommission other = (UserInviteCommission) that;
        return (this.getUserInviteCommissionId() == null ? other.getUserInviteCommissionId() == null : this.getUserInviteCommissionId().equals(other.getUserInviteCommissionId()))
            && (this.getTeamId() == null ? other.getTeamId() == null : this.getTeamId().equals(other.getTeamId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getInviteUserId() == null ? other.getInviteUserId() == null : this.getInviteUserId().equals(other.getInviteUserId()))
            && (this.getOperationType() == null ? other.getOperationType() == null : this.getOperationType().equals(other.getOperationType()))
            && (this.getLvl() == null ? other.getLvl() == null : this.getLvl().equals(other.getLvl()))
            && (this.getRate() == null ? other.getRate() == null : this.getRate().equals(other.getRate()))
            && (this.getCommissionSum() == null ? other.getCommissionSum() == null : this.getCommissionSum().equals(other.getCommissionSum()))
            && (this.getRefId() == null ? other.getRefId() == null : this.getRefId().equals(other.getRefId()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getStateType() == null ? other.getStateType() == null : this.getStateType().equals(other.getStateType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserInviteCommissionId() == null) ? 0 : getUserInviteCommissionId().hashCode());
        result = prime * result + ((getTeamId() == null) ? 0 : getTeamId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getInviteUserId() == null) ? 0 : getInviteUserId().hashCode());
        result = prime * result + ((getOperationType() == null) ? 0 : getOperationType().hashCode());
        result = prime * result + ((getLvl() == null) ? 0 : getLvl().hashCode());
        result = prime * result + ((getRate() == null) ? 0 : getRate().hashCode());
        result = prime * result + ((getCommissionSum() == null) ? 0 : getCommissionSum().hashCode());
        result = prime * result + ((getRefId() == null) ? 0 : getRefId().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getStateType() == null) ? 0 : getStateType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invite_commission
     *
     * @mbg.generated Mon May 18 21:11:11 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userInviteCommissionId=").append(userInviteCommissionId);
        sb.append(", teamId=").append(teamId);
        sb.append(", userId=").append(userId);
        sb.append(", inviteUserId=").append(inviteUserId);
        sb.append(", operationType=").append(operationType);
        sb.append(", lvl=").append(lvl);
        sb.append(", rate=").append(rate);
        sb.append(", commissionSum=").append(commissionSum);
        sb.append(", refId=").append(refId);
        sb.append(", memo=").append(memo);
        sb.append(", createTime=").append(createTime);
        sb.append(", stateType=").append(stateType);
        sb.append("]");
        return sb.toString();
    }
}